---
title: "Hmk5"
output: html_document
author : "Ziyi Tao"
---

Github: <https://github.com/t-aozy/Hmk5-STAT506>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1 OOP Programming

### a. Create class

```{r}
# 1 define constructor
rational <- setClass("rational", 
                     slots = c(nume = "numeric",
                               deno = "numeric" )
                     )

def_rational <- function(nume, deno){
  return(new("rational", nume = nume, deno = deno))
}


# 2 define validator
setValidity("rational", function(object){
  if(object@deno == 0){
    stop("Denominator is zero")
  }
  if(object@deno %% 1 != 0 | object@nume %% 1 != 0){
    stop("Denominator and numerator must be integer.")
  }
  return(TRUE)
})


# 3 define show method
setMethod("show", "rational", 
          function(object){
            
            if(object@deno == 1 | object@nume == 0){
              cat(object@nume/object@deno)
            }
            else{
            cat(
              paste(
                c(object@nume, "/", object@deno, "\n"),
                collapse = "")
            )
            }
            return(invisible(object))
          }
  )


# 4 simplify method
library(Rcpp)
cppFunction("
  int C_gcd(int x, int y){
    return std :: gcd(x, y);
  }"
)

setGeneric("simplify",
           function(object){
             standardGeneric("simplify")
           })
setMethod("simplify", "rational",
          function(object){
            gcd_ <- C_gcd(object@nume, object@deno)
            new_rational <- def_rational(object@nume/gcd_,
                                         object@deno/gcd_)
            return(new_rational)
          })



# 5 quotient method

setGeneric("quotient",
           function(object, digits = 2){
             standardGeneric("quotient")
           })
setMethod("quotient", "rational",
          function(object, digits = 2){
            if(is.character(digits) == TRUE){
              stop("digits should be integer")
            }
            if(digits %% 1 != 0){
              stop("digits should be integer")
            }
            print(object@nume/object@deno, digits = digits)
            return(invisible(object))
          })


# 6 + - * /
setMethod("+", signature(e1 = "rational", 
                         e2 = "rational"),
          function(e1, e2){
            new_deno <- e1@deno * e2@deno
            new_nume <- e1@nume*e2@deno + e2@nume*e1@deno
            new_r <- simplify(def_rational(new_nume, new_deno))
            
            return(invisible(new_r))
          })

setMethod("-", signature(e1 = "rational", 
                         e2 = "rational"),
          function(e1, e2){
            new_deno <- e1@deno * e2@deno
            new_nume <- e1@nume*e2@deno - e2@nume*e1@deno
            new_r <- def_rational(new_nume, new_deno)
            return(invisible(simplify(new_r)))
          })

setMethod("*", signature(e1 = "rational", 
                         e2 = "rational"),
          function(e1, e2){
            new_deno <- e1@deno * e2@deno
            new_nume <- e2@nume * e1@nume
            new_r <- def_rational(new_nume, new_deno)
            return(invisible(simplify(new_r)))
          })

setMethod("/", signature(e1 = "rational", 
                         e2 = "rational"),
          function(e1, e2){
            if(e2@nume == 0){
              stop("divisor is zero")
            }
            new_deno <- e1@deno * e2@nume
            new_nume <- e2@deno * e1@nume
            new_r <- def_rational(new_nume, new_deno)
            return(invisible(simplify(new_r)))
          })


```

### b. Create objects and test

```{r}
r1 <- def_rational(24, 6)
r2 <- def_rational(7, 230)
r3 <- def_rational(0, 4)
```

```{r, error= TRUE}
r1
r3
r1 + r2
r1 - r2
r1*r2
r1/r2
r1+r3
r1*r3
r2/r3

## we set default digits = 2
quotient(r1)
quotient(r2)
quotient(r2, digits = 3)
quotient(r2, digits = 3.14)
quotient(r2, digits = "avocado")

q2 <- quotient(r2, digits = 3)
q2
quotient(r3)

simplify(r1)
simplify(r2)
simplify(r3)
```

### c. Test Error

```{r, error=TRUE}
def_rational(3, 0)
```

```{r, error = TRUE}
def_rational(1.34, 2)
```

```{r, error=TRUE}
def_rational("h", "h")
```

## Problem 2

```{r}

library(ggplot2)
library(scales)
library(plotly)
library(ggsci)
library(dplyr)

data <- read.csv("D:/df_for_ml_improved_new_market.csv")

data$year <- as.factor(data$year)


data %>% 
  group_by(year)%>% 
  summarize(
      photo = sum(Genre___Photography),
      print = sum(Genre___Print),
      paintng = sum(Genre___Painting),
      sculpture = sum(Genre___Sculpture),
      other = sum(Genre___Others)
    )%>%
  tidyr:: pivot_longer(cols = !year)%>%
  mutate(genre = name,
         count = value
         )%>%
  select(year, genre, count) -> data_genre

data_genre %>% group_by(year)%>% 
  mutate(ratio = round(count/sum(count), digit = 2)) -> data_genre

g <- ggplot(data_genre, aes(x = year, y = count, fill = genre))+
  geom_bar(stat = "identity", position = "fill")+
  xlab("YEAR")+
  ylab("PROPORTION")+
  theme_classic()+
  geom_text(aes(label = ratio), 
            position = position_fill(0.8), size = 3, vjust = 0.5)+
  scale_y_continuous(expand = c(0, 0))+
  scale_fill_npg()

ggplotly(g)
```

```{r}
data$genre <- 1*data$Genre___Sculpture + 2*data$Genre___Painting+
              3*data$Genre___Print+ 4*data$Genre___Photography

data <- data[data$genre!=0,]

data %>%
  group_by(year)%>%
  summarize(
    mean_price = mean(price_usd),
    quantile_95 = quantile(price_usd, 0.95)
  ) -> data_all

data %>% 
  group_by(year, genre)%>% 
  summarize(
      mean_price = mean(price_usd),
      quantile_95 = quantile(price_usd, 0.95)
    )%>%
  tidyr:: pivot_wider(names_from = c(genre), values_from = c(mean_price, quantile_95))  -> data_genre_1

data_genre_1$year <- as.numeric(data_genre_1$year)

p <- plot_ly() |>
  add_lines(x = 1997:2012, 
            y = data_genre_1$mean_price_1, name = "mean") |>
  add_lines(x = 1997:2012, 
            y = data_genre_1$quantile_95_1, name = "95%") |>
  add_lines(x = 1997:2012, 
            y = data_genre_1$mean_price_2, visible = FALSE, name = "mean") |>
  add_lines(x = 1997:2012, 
            y = data_genre_1$quantile_95_2, visible = FALSE, name = "95%") |>
  add_lines(x = 1997:2012, 
            y = data_genre_1$mean_price_3, visible = FALSE, name = "mean") |>
  add_lines(x = 1997:2012, 
            y = data_genre_1$quantile_95_3, visible = FALSE, name = "95%") |>
  add_lines(x = 1997:2012, 
            y = data_genre_1$mean_price_4, visible = FALSE, name = "mean") |>
  add_lines(x = 1997:2012, 
            y = data_genre_1$quantile_95_4, visible = FALSE, name = "95%")|>
  add_lines(x = 1997:2012, 
            y = data_all$mean_price, visible = FALSE, name = "mean") |>
  add_lines(x = 1997:2012, 
            y = data_all$quantile_95, visible = FALSE, name = "95%")

```

```{r}
p |> layout(updatemenus = list(
  list(
    y = 1,
    x = -0.1,
    buttons = list(
      list(method = "update",
           args = list(list(visible =  list(TRUE, TRUE, 
                                            FALSE, FALSE, 
                                            FALSE, FALSE,
                                            FALSE, FALSE,
                                            FALSE, FALSE)),
                       list(yaxis = list(title = "o3"))),
           label = "Sculpture"),

      list(method = "update",
           args = list(list(visible =  list(FALSE, FALSE,
                                            TRUE, TRUE,
                                            FALSE, FALSE,
                                            FALSE, FALSE,
                                            FALSE, FALSE)),
                       list(yaxis = list(title = "temp"))),
           label = "Print"),
    
      list(method = "update",
             args = list(list(visible =  list(FALSE, FALSE,
                                              FALSE, FALSE,
                                              TRUE, TRUE,
                                              FALSE, FALSE,
                                              FALSE, FALSE)),
                         list(yaxis = list(title = "temp"))),
             label = "Paint"),
      
      list(method = "update",
             args = list(list(visible = list(FALSE, FALSE,
                                             FALSE, FALSE, 
                                             FALSE, FALSE,
                                             TRUE, TRUE,
                                             FALSE, FALSE)),
                         list(yaxis = list(title = "temp"))),
             label = "Photo"),
      
      list(method = "update",
             args = list(list(visible = list(FALSE, FALSE,
                                             FALSE, FALSE, 
                                             FALSE, FALSE,
                                             FALSE, FALSE,
                                             TRUE, TRUE)),
                         list(yaxis = list(title = "temp"))),
             label = "Overall"))
)))
```

## Problem 3

```{r}
library(nycflights13)

library(dplyr)
library(data.table)

flights <- data.table(nycflights13::flights) 


# merge airport and flights
flights_airport_dep <- merge(flights, 
                             nycflights13::airports, 
                             by.x = "origin", by.y = "faa" )

# dest with <= 10 flights
origins <- flights_airport_dep[, .(count = .N), by = origin]$origin

# filter flights, compute mean and median, order
flights_airport_dep[origin %in% origins][, 
                                         .(mean_dep_delay = 
                                             mean(dep_delay, na.rm = TRUE),
                                           median_dep_delay = 
                                             median(dep_delay, na.rm = TRUE)),
                                         by = name][order(-mean_dep_delay)]


```

```{r}

# merge airport and flights
flights_airport_arr <- merge(flights, nycflights13::airports, 
                             by.x = "dest", by.y = "faa")

# dest with <= 10 flights
dests <- flights_airport_arr[, .(count = .N), by = "dest"][count >= 10]$dest

# filter flights, compute mean and median, order
flights_airport_arr[dest %in% dests][, 
                                         .(mean_arr_delay = 
                                             mean(arr_delay, na.rm = TRUE),
                                           median_arr_delay = 
                                             median(arr_delay, na.rm = TRUE)),
                                         by = name][order(-mean_arr_delay)]


```

```{r}

flights <- data.table(nycflights13::flights) 
flights_plane <- merge(flights, nycflights13 :: planes, by = "tailnum")

flights_plane[, mph := distance /(air_time/60)][
  ,  .(mean_speed = mean(mph, na.rm = TRUE), count = .N), by = model][
    mean_speed == max(mean_speed)]

```
